// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWIUJVkB1jawmFon33gUjvXVp9VuHHuik',
    appId: '1:473956346033:web:42a1dfbb380efb29885a90',
    messagingSenderId: '473956346033',
    projectId: 'arthur-practice',
    authDomain: 'arthur-practice.firebaseapp.com',
    storageBucket: 'arthur-practice.appspot.com',
    measurementId: 'G-QLDHQ5VGJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_0RNQMWrcKKrW09Yw_NL3FjMTia-C4Tw',
    appId: '1:473956346033:android:ce899fd4a048f14a885a90',
    messagingSenderId: '473956346033',
    projectId: 'arthur-practice',
    storageBucket: 'arthur-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPNHbxW5ousmHEaiz7u3dxon1HZBzpSlI',
    appId: '1:473956346033:ios:4f2cf0d7c20918ad885a90',
    messagingSenderId: '473956346033',
    projectId: 'arthur-practice',
    storageBucket: 'arthur-practice.appspot.com',
    androidClientId: '473956346033-cko80ircqt1fj3sc69muov5etie6eukq.apps.googleusercontent.com',
    iosClientId: '473956346033-j60kmqadldc8lvm4094bh933kl956t5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPracticeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPNHbxW5ousmHEaiz7u3dxon1HZBzpSlI',
    appId: '1:473956346033:ios:a5b526fa039ced45885a90',
    messagingSenderId: '473956346033',
    projectId: 'arthur-practice',
    storageBucket: 'arthur-practice.appspot.com',
    androidClientId: '473956346033-cko80ircqt1fj3sc69muov5etie6eukq.apps.googleusercontent.com',
    iosClientId: '473956346033-toie5rrn80fbatl9jhqp9ncv0o9fo1n9.apps.googleusercontent.com',
    iosBundleId: 'e.g',
  );
}
